from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from apps.kyzo_backend.config import KnowledgeMessages, QuestionMessages
from apps.kyzo_backend.core import get_db
from apps.kyzo_backend.managers import QuestionManager
from apps.kyzo_backend.schemas import (QuestionInputUpdate,
                                       QuestionInputCreate,
                                       QuestionInputRead,
                                       QuestionUpdate,
                                       QuestionRead,
                                       QuestionStatus)

router = APIRouter(
    prefix="/api/questions",
    tags=["Questions"]
)


@router.post("/inputs/add", status_code=status.HTTP_201_CREATED)
async def add_question(
        question_count: int,
        question_input_data: QuestionInputCreate,
        db: Session = Depends(get_db)
):
    """
    Initiates the AI-driven question generation pipeline.

    This endpoint performs the following orchestration:
    1. **Context Validation**: Ensures the provided Subject and Topic IDs exist.
    2. **AI Extraction**: Sends the raw content to the LLM to generate the
       requested number of question drafts.
    3. **Draft Storage**: Persists the results in a `QuestionInput` record.

    **Note**: This does not yet create active questions in the main pool.
    Use the `/finalize` endpoint to promote these drafts after review.

    Args:
        question_count (int): Number of questions to be generated by the AI.
        question_input_data (QuestionInputCreate): The source material and metadata.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        str: A success message confirming the number of drafted questions.

    Raises:
        HTTPException (404): If the subject or topic is not found.
        HTTPException (500): If the AI generation or database persistence fails.
    """
    question_manager = QuestionManager(db)

    success, result = question_manager.add_question_input(
        question_count,
        question_input_data
    )

    if not success:
        if result in (
                KnowledgeMessages.SUBJECT_NOT_FOUND,
                KnowledgeMessages.TOPIC_NOT_FOUND):
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result


@router.post("/inputs/{question_input_id}/finalize", status_code=status.HTTP_201_CREATED)
async def finalize_input(question_input_id: int, db: Session = Depends(get_db)):
    """
    Promotes AI-generated drafts to the permanent global question pool.

    This endpoint finalizes a generation job by:
    1. **Validation**: Checking if drafts exist and haven't been processed yet.
    2. **Transformation**: Creating permanent `Question` records from the drafts.
    3. **Linking**: Establishing a `QuestionOrigin` to maintain traceability.
    4. **Locking**: Setting `is_processed = True` to prevent duplicate promotion.

    **Idempotency**: This operation can only be performed once per Input ID.
    Subsequent calls will result in a 400 Bad Request.

    Args:
        question_input_id (int): The ID of the QuestionInput record to be finalized.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        str: A success message confirming the number of questions added to the pool.

    Raises:
        HTTPException (400): If the input is already processed or contains no drafts.
        HTTPException (404): If the question_input_id is not found.
        HTTPException (500): If the database transaction fails.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.create_questions_from_question_input(question_input_id)

    if not success:
        if result == QuestionMessages.QUESTION_INPUT_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        if "Error" in result or QuestionMessages.CREATE_QUESTION_ERROR in result:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=result
        )

    return result


@router.post("/inputs/{question_input_id}/ai-generate")
async def extract_questions_from_raw_input(
        question_input_id: int,
        num_of_questions: int,
        db: Session = Depends(get_db)):
    """
    Manually triggers AI question generation for a specific raw input record.

    This endpoint allows users to (re-)run the AI extraction process for a
    previously saved QuestionInput. It is primarily used as a fallback
    mechanism if the automatic generation during the initial upload failed
    or was skipped.

    Args:
        question_input_id (int): The unique ID of the QuestionInput to process.
        num_of_questions (int): The number of questions the AI should attempt
            to generate from the source text.
        db (Session): Database session injected via FastAPI dependency.

    Returns:
        str: A success message containing the count of generated questions
            upon successful completion.

    Raises:
        HTTPException:
            - 404 Not Found: If the `question_input_id` does not exist.
            - 400 Bad Request: If the input has already been processed or
              the AI generation parameters are invalid.
            - 500 Internal Server Error: If a database error (SQLAlchemy)
              or an unexpected generation error occurs.
    """
    question_manager = QuestionManager(db)

    success, result = question_manager.extract_questions_from_raw_input(
        question_input_id,
        num_of_questions
    )

    if not success:
        if result == QuestionMessages.QUESTION_INPUT_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        if "Error" in result or QuestionMessages.CREATE_QUESTION_ERROR in result:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=result
        )

    return result




@router.get("/list-all", response_model=list[QuestionRead])
async def get_questions(db: Session = Depends(get_db)):
    """
    Retrieves the complete list of all questions available in the global pool.

    This endpoint returns every question across all subjects and topics.
    It is primarily used for administrative overview or broad content audits.

    Args:
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        list[QuestionRead]: A list of all questions, formatted according to the
                           QuestionRead schema.

    Raises:
        HTTPException (404): If the question pool is currently empty.
        HTTPException (500): If a database error occurs during retrieval.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.get_all_questions()

    if not success:
        if result == QuestionMessages.QUESTION_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result


@router.get("/subjects/{subject_id}", response_model=list[QuestionRead])
async def get_questions_for_subject(subject_id: int, db: Session = Depends(get_db)):
    """
    Retrieves all questions filtered by a specific subject.

    This endpoint is used for subject-specific browsing or quiz generation.
    It returns a filtered subset of the global question pool based on the
    provided subject identifier.

    Args:
        subject_id (int): The unique ID of the subject to filter by.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        list[QuestionRead]: A list of questions belonging to the specified subject.

    Raises:
        HTTPException (404): If no questions are found for the given subject ID.
        HTTPException (500): If a database error occurs during retrieval.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.get_questions_for_subject_topic(subject_id)

    if not success:
        if result == QuestionMessages.QUESTION_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result


@router.get("/subjects/{subject_id}/topics/{topic_id}", response_model=list[QuestionRead])
async def get_questions_for_subject_topic(
        subject_id: int,
        topic_id: int,
        db: Session = Depends(get_db)
):
    """
    Retrieves questions filtered by both subject and a specific topic.

    This is the most granular retrieval endpoint, ideal for targeted practice
    sessions or specific classroom modules. It ensures that the returned
    questions belong strictly to the intersection of the given subject and topic.

    Args:
        subject_id (int): The unique ID of the subject.
        topic_id (int): The unique ID of the topic within that subject.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        list[QuestionRead]: A list of questions matching both criteria.

    Raises:
        HTTPException (404): If no questions exist for this specific combination.
        HTTPException (500): If a database error occurs during the query.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.get_questions_for_subject_topic(
        subject_id,
        topic_id
    )

    if not success:
        if result == QuestionMessages.QUESTION_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result


@router.get("/{question_id}", response_model=QuestionRead)
async def get_question_by_id(question_id: int, db: Session = Depends(get_db)):
    """
    Retrieves a single question from the global pool by its unique identifier.

    This endpoint is used when the specific ID of a question is already known,
    e.g., when loading a single question for detailed viewing, editing,
    or specific pedagogical review.

    Args:
        question_id (int): The unique primary key of the question.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        QuestionRead: The complete question data matching the ID.

    Raises:
        HTTPException (404): If no question exists with the provided ID.
        HTTPException (500): If a database error occurs during retrieval.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.get_question_by_id(question_id)

    if not success:
        if result == QuestionMessages.QUESTION_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result


@router.get("/inputs/{question_input_id}", response_model=QuestionInputRead)
async def get_question_input_by_id(question_input_id: int, db: Session = Depends(get_db)):
    """
    Retrieves a specific question generation job and its AI-generated drafts.

    This endpoint is used to check the progress of a generation request or to
    fetch the raw drafts for user review and potential editing before they
    are promoted to the global pool.

    Args:
        question_input_id (int): The unique identifier of the generation job.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        QuestionInputRead: The full record including raw input, drafts, and status.

    Raises:
        HTTPException (404): If the specified ID does not exist.
        HTTPException (500): If a database error occurs.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.get_question_input_by_id(question_input_id)

    if not success:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=QuestionMessages.QUESTION_INPUT_NOT_FOUND
        )

    return result


@router.put("/{question_id}/status", response_model=QuestionRead)
async def set_question_status(
        question_id: int,
        active: QuestionStatus,
        db: Session = Depends(get_db)
):
    """
    Toggles the visibility or operational status of a specific question.

    This endpoint is used to enable or disable questions in the live pool
    without deleting them. This is useful for temporary removals, content
    reviews, or retiring outdated questions while maintaining database
    integrity and historical records.

    Args:
        question_id (int): The unique ID of the question to update.
        active (QuestionStatus): True to activate the question, False to deactivate it.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        QuestionRead: The updated question record reflecting the new status.

    Raises:
        HTTPException (404): If the question_id does not exist.
        HTTPException (500): If the status update fails due to a database error.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.set_question_status(question_id, active)

    if not success:
        if result == QuestionMessages.QUESTION_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result


@router.put("/inputs/{question_input_id}/edit", response_model=QuestionInputRead)
async def update_question_input(
        question_input_id: int,
        question_input_data: QuestionInputUpdate,
        db: Session = Depends(get_db)
):
    """
    Updates an existing question generation job before finalization.

    This endpoint is the 'Review & Edit' hub. It allows users to correct
    metadata (like grade or topic) or the raw input text after the AI has
    generated drafts. This step ensures data integrity before questions are
    permanently promoted to the global pool.

    Args:
        question_input_id (int): The unique ID of the QuestionInput record.
        question_input_data (QuestionInputUpdate): The partial data to update.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        QuestionInputRead: The updated record including all current drafts.

    Raises:
        HTTPException (404): If the specific QuestionInput ID does not exist.
        HTTPException (500): If a database or internal processing error occurs.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.update_question_input(
        question_input_id,
        question_input_data
    )

    if not success:
        if result == QuestionMessages.QUESTION_INPUT_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result


@router.put("/{question_id}/edit", response_model=QuestionRead)
async def update_question_by_id(
        question_id: int,
        question_data: QuestionUpdate,
        db: Session = Depends(get_db)
):
    """
    Updates the content or properties of an existing question.

    This endpoint allows for granular changes to a question that is already
    in the live pool, such as fixing typos, updating answer options,
    or adjusting the difficulty level.

    Args:
        question_id (int): The unique identifier of the question to be updated.
        question_data (QuestionUpdate): The DTO containing the fields to update.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        QuestionRead: The updated question record.

    Raises:
        HTTPException (404): If no question is found with the provided ID.
        HTTPException (500): If the update fails due to a database error.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.update_question(question_id, question_data)

    if not success:
        if result == QuestionMessages.QUESTION_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result
