from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from apps.kyzo_backend.config import KnowledgeMessages, QuestionMessages
from apps.kyzo_backend.core import get_db
from apps.kyzo_backend.managers import QuestionManager
from apps.kyzo_backend.schemas import (QuestionInputUpdate,
                                       QuestionInputCreate,
                                       QuestionInputRead)

router = APIRouter(
    prefix="/api/questions",
    tags=["Questions"]
)


@router.post("/add", status_code=status.HTTP_201_CREATED)
async def add_question(
        question_count: int,
        question_input_data: QuestionInputCreate,
        db: Session = Depends(get_db)
):
    """
    Initiates the AI-driven question generation pipeline.

    This endpoint performs the following orchestration:
    1. **Context Validation**: Ensures the provided Subject and Topic IDs exist.
    2. **AI Extraction**: Sends the raw content to the LLM to generate the
       requested number of question drafts.
    3. **Draft Storage**: Persists the results in a `QuestionInput` record.

    **Note**: This does not yet create active questions in the main pool.
    Use the `/finalize` endpoint to promote these drafts after review.

    Args:
        question_count (int): Number of questions to be generated by the AI.
        question_input_data (QuestionInputCreate): The source material and metadata.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        str: A success message confirming the number of drafted questions.

    Raises:
        HTTPException (404): If the subject or topic is not found.
        HTTPException (500): If the AI generation or database persistence fails.
    """
    question_manager = QuestionManager(db)

    success, result = question_manager.add_question_input(
        question_count,
        question_input_data
    )

    if not success:
        if result in (
                KnowledgeMessages.SUBJECT_NOT_FOUND,
                KnowledgeMessages.TOPIC_NOT_FOUND):
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result


@router.get("/inputs/{question_input_id}", response_model=QuestionInputRead)
async def get_question_input_by_id(question_input_id: int, db: Session = Depends(get_db)):
    """
    Retrieves a specific question generation job and its AI-generated drafts.

    This endpoint is used to check the progress of a generation request or to
    fetch the raw drafts for user review and potential editing before they
    are promoted to the global pool.

    Args:
        question_input_id (int): The unique identifier of the generation job.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        QuestionInputRead: The full record including raw input, drafts, and status.

    Raises:
        HTTPException (404): If the specified ID does not exist.
        HTTPException (500): If a database error occurs.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.get_question_input_by_id(question_input_id)

    if not success:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    if result is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=QuestionMessages.QUESTION_INPUT_NOT_FOUND
        )

    return result


@router.post("/inputs/{question_input_id}/finalize", status_code=status.HTTP_201_CREATED)
async def finalize_input(question_input_id: int, db: Session = Depends(get_db)):
    """
    Promotes AI-generated drafts to the permanent global question pool.

    This endpoint finalizes a generation job by:
    1. **Validation**: Checking if drafts exist and haven't been processed yet.
    2. **Transformation**: Creating permanent `Question` records from the drafts.
    3. **Linking**: Establishing a `QuestionOrigin` to maintain traceability.
    4. **Locking**: Setting `is_processed = True` to prevent duplicate promotion.

    **Idempotency**: This operation can only be performed once per Input ID.
    Subsequent calls will result in a 400 Bad Request.

    Args:
        question_input_id (int): The ID of the QuestionInput record to be finalized.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        str: A success message confirming the number of questions added to the pool.

    Raises:
        HTTPException (400): If the input is already processed or contains no drafts.
        HTTPException (404): If the question_input_id is not found.
        HTTPException (500): If the database transaction fails.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.create_questions_from_question_input(question_input_id)

    if not success:
        if result == QuestionMessages.QUESTION_INPUT_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        if "Error" in result or QuestionMessages.CREATE_QUESTION_ERROR in result:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=result
        )

    return result


@router.put("/inputs/{question_input_id}/edit", response_model=QuestionInputRead)
async def edit_question_input(
        question_input_id: int,
        question_input_data: QuestionInputUpdate,
        db: Session = Depends(get_db)
):
    """
    Updates an existing question generation job before finalization.

    This endpoint is the 'Review & Edit' hub. It allows users to correct
    metadata (like grade or topic) or the raw input text after the AI has
    generated drafts. This step ensures data integrity before questions are
    permanently promoted to the global pool.

    Args:
        question_input_id (int): The unique ID of the QuestionInput record.
        question_input_data (QuestionInputUpdate): The partial data to update.
        db (Session): The database session provided by the FastAPI dependency.

    Returns:
        QuestionInputRead: The updated record including all current drafts.

    Raises:
        HTTPException (404): If the specific QuestionInput ID does not exist.
        HTTPException (500): If a database or internal processing error occurs.
    """
    question_manager = QuestionManager(db)
    success, result = question_manager.update_question_input(
        question_input_id,
        question_input_data
    )

    if not success:
        if result == QuestionMessages.QUESTION_INPUT_NOT_FOUND:
            raise HTTPException(
                status_code=status.HTTP_404_NOT_FOUND,
                detail=result
            )

        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=result
        )

    return result
